### ISSUE TITLE
Feedback: 不能复制

### ISSUE THREAD

**Issue by CrazySir** [ExistOrLive/GithubClient#34]
不能复制 
 >iOS14.6 - iPhone X - ZLGithubClient1.0.6(28)

**Comment by ExistOrLive** [comment]
你好，请问希望在哪里添加复制功能

**Comment by CrazySir** [comment]
其实很多时候都是需要用到复制的，比如昵称，最重要的是文件里应该是必须得有的。
还有一个raw的建议，有没有可能在文件列表长按某个文件可以直接复制raw链接的选项







------------------ 原始邮件 ------------------
发件人: 朱猛 ***@***.***&gt;
发送时间: 2021年7月29日 19:15
收件人: ExistOrLive/GithubClient ***@***.***&gt;
抄送: CrazySir ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ExistOrLive/GithubClient] Feedback: 不能复制 (#34)





 
你好，请问希望在哪里添加复制功能
