### ISSUE TITLE
github api 的 userprofile  的 profileReadme 能获取吗？官方的 app  能获取到

### ISSUE THREAD

**Issue by JeffreyBool** [ExistOrLive/GithubClient#36]
github app 授权登录的 token , 获取用的中心的 readme  能获取到，自己 oauth  授权的 token 获取不到 userpro  的 profileReadme 字段

···json
{
	"operationName": "UserProfile",
	"query": "query UserProfile($username: String!, $headerAvatarSize: Int!, $avatarSize: Int!) {\n  user(login: $username) {\n    __typename\n    ...UserProfileFragment\n  }\n  organization(login: $username) {\n    __typename\n    ...OrganizationFragment\n  }\n}\nfragment UserProfileFragment on User {\n  __typename\n  avatarUrl(size: $headerAvatarSize)\n  id\n  bioHTML\n  companyHTML\n  email\n  followers {\n    __typename\n    totalCount\n  }\n  following {\n    __typename\n    totalCount\n  }\n  isDeveloperProgramMember\n  isGitHubStar\n  githubStarsProfileUrl\n  isEmployee\n  isViewer\n  itemShowcase {\n    __typename\n    hasPinnedItems\n    items(first: 6) {\n      __typename\n      nodes {\n        __typename\n        ... on Repository {\n          ...ModernRepositoryListItemFragment\n        }\n      }\n    }\n  }\n  location\n  login\n  name\n  organizations {\n    __typename\n    totalCount\n  }\n  repositories(ownerAffiliations: [OWNER]) {\n    __typename\n    totalCount\n  }\n  sponsorshipsAsSponsor {\n    __typename\n    totalCount\n  }\n  starredRepositories {\n    __typename\n    totalCount\n  }\n  status {\n    __typename\n    emoji\n    indicatesLimitedAvailability\n    message\n  }\n  showProfileReadme\n  profileReadme {\n    __typename\n    contentHTML\n  }\n  viewerCanFollow\n  viewerCanBlock\n  viewerCanUnblock\n  viewerIsFollowing\n  websiteUrl\n}\nfragment ModernRepositoryListItemFragment on Repository {\n  __typename\n  id\n  primaryLanguage {\n    __typename\n    name\n    color\n  }\n  name\n  owner {\n    __typename\n    login\n    ...ModernAvatarFragment\n  }\n  shortDescriptionHTML\n  descriptionHTML\n  stargazerCount\n  parent {\n    __typename\n    name\n    owner {\n      __typename\n      login\n    }\n  }\n  usesCustomOpenGraphImage\n  openGraphImageUrl\n  viewerHasStarred\n  hasIssuesEnabled\n  isDiscussionsEnabled\n  isArchived\n}\nfragment ModernAvatarFragment on Actor {\n  __typename\n  avatarUrl(size: $avatarSize)\n}\nfragment OrganizationFragment on Organization {\n  __typename\n  avatarUrl(size: $headerAvatarSize)\n  id\n  descriptionHTML\n  email\n  isVerified\n  itemShowcase {\n    __typename\n    hasPinnedItems\n    items(first: 6) {\n      __typename\n      nodes {\n        __typename\n        ... on Repository {\n          ...ModernRepositoryListItemFragment\n        }\n      }\n    }\n  }\n  location\n  login\n  name\n  repositories(ownerAffiliations: [OWNER]) {\n    __typename\n    totalCount\n  }\n  websiteUrl\n  sponsorshipsAsSponsor {\n    __typename\n    totalCount\n  }\n}",
	"variables": {
		"avatarSize": 72,
		"headerAvatarSize": 192,
		"username": "JeffreyBool"
	}
}
```

**Comment by JeffreyBool** [comment]
{
            "path": [
                "fragment UserProfileFragment",
                "profileReadme"
            ],
            "extensions": {
                "code": "undefinedField",
                "typeName": "User",
                "fieldName": "profileReadme"
            },
            "locations": [
                {
                    "line": 70,
                    "column": 3
                }
            ],
            "message": "Field 'profileReadme' doesn't exist on type 'User'"
        },

**Comment by ExistOrLive** [comment]
最新的github graphql api 可以参考[public schema](https://docs.github.com/en/graphql/overview/public-schema)。 
目前为止，**profileReadme** 这个字段应该是没有提供给第三方使用
