### ISSUE TITLE
Feedback: 不知道有没有人反馈过，现在右上角三个点那个分享到safari和到github是反过来的

### ISSUE THREAD

**Issue by sunlc123** [ExistOrLive/GithubClient#41]
不知道有没有人反馈过，现在右上角三个点那个分享到safari和到github是反过来的 
 >iOS15.2.1 - iPhone 13 Pro - ZLGithubClient1.1.0(46)

**Comment by ExistOrLive** [comment]
如果你安装GitHub官方app，在safari打开github之后，会自动导航到官方app
