### ISSUE TITLE
Feedback: issue查不到

### ISSUE THREAD

**Issue by hczs** [ExistOrLive/GithubClient#42]
issue查不到 
 >iPadOS15.2.1 - iPad 9 - ZLGithubClient1.1.0(46)

**Comment by hczs** [comment]
我理解错了，原来是查我发起的issue，我还以为是查的待办通知........

**Comment by ExistOrLive** [comment]
现在Github暂时还没有开发查询待办的issue的API

**Comment by hczs** [comment]
> 现在Github暂时还没有开发查询待办的issue的API 

嗯嗯，软件很好用！祝越做越好！

**Comment by ExistOrLive** [comment]
> > 现在Github暂时还没有开发查询待办的issue的API
> 
> 嗯嗯，软件很好用！祝越做越好！

非常感谢您的回复，如果您觉的可以的话，希望您能给个好评或者星星 ^_^
