### ISSUE TITLE
Feedback: The profile tab‘s over small check not turn green

### ISSUE THREAD

**Issue by Oliverwqcwrw** [ExistOrLive/GithubClient#45]
The profile tab‘s over small check not turn green 
 >iOS15.4 - iPhone 12 mini - ZLGithubClient1.1.0(46)

**Comment by ZXHubs** [comment]
Maybe it's a network problem. Will it be updated later? It may also be the problem of binding the mailbox of the account.

**Comment by ExistOrLive** [comment]
Is the contributions view in app different from in github offical website ？

**Comment by Oliverwqcwrw** [comment]
yes
    	Get Outlook for iOS
    
  

 From: ***@***.*** ***@***.***> on behalf of 朱猛 ***@***.***>Sent: Sunday, March 27, 2022 17:15To: ExistOrLive/GithubClient ***@***.***>Cc: Oliver ***@***.***>; Author ***@***.***>Subject: Re: [ExistOrLive/GithubClient] Feedback: The profile tab‘s over small check not turn green (Issue #45) 

Is the contributions view in app different from in github offical website ？

**Comment by Oliverwqcwrw** [comment]
and it always display empty contributions view
    	Get Outlook for iOS
    
  

 From: ***@***.*** ***@***.***>Sent: Sunday, March 27, 2022 17:24To: ExistOrLive/GithubClient ***@***.***>; ExistOrLive/GithubClient ***@***.***>Cc: Author ***@***.***>Subject: Re: [ExistOrLive/GithubClient] Feedback: The profile tab‘s over small check not turn green (Issue #45) 
  
  
  
    
    	
    	yes
    	Get Outlook for iOS
    
  

 From: ***@***.*** ***@***.***> on behalf of 朱猛 ***@***.***>Sent: Sunday, March 27, 2022 17:15To: ExistOrLive/GithubClient ***@***.***>Cc: Oliver ***@***.***>; Author ***@***.***>Subject: Re: [ExistOrLive/GithubClient] Feedback: The profile tab‘s over small check not turn green (Issue #45) 

Is the contributions view in app different from in github offical website ？

**Comment by ExistOrLive** [comment]
In 1.1.0，we get contributions data from github website‘s profile page ，so only public data can be got. In next version, the problem will be solved by using github graphql api . 

You can try the beta version with the following link： 
https://testflight.apple.com/join/kCFO5joL

**Comment by Oliverwqcwrw** [comment]
OK, thank you
