### ISSUE TITLE
Feedback: 仓库https://github.com/Anduin2017/HowToCook，readme中《厨房准备》链接打开404，pc可能正常使用，我对比了一下url，区别如下

https://github.com/Anduin2017/HowToCook/blob/master/tips/%E5%8E%A8%E6%88%BF%E5%87%86%E5%A4%87.md
https://github.com/Anduin2017/HowToCook/blob/master/tips/%25E5%258E%25A8%25E6%2588%25BF%25E5%2587%2586%25E5%25A4%2587.md
第一个是github pc上打开的，可以正常使用，第二个我通过app打开的，会404，我见到的排查了一下，第二个url应该是经过了2次urlEncode转换，所以会导致404

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [ExistOrLive/GithubClient#49]
仓库https://github.com/Anduin2017/HowToCook，readme中《厨房准备》链接打开404，pc可能正常使用，我对比了一下url，区别如下

https://github.com/Anduin2017/HowToCook/blob/master/tips/%E5%8E%A8%E6%88%BF%E5%87%86%E5%A4%87.md
https://github.com/Anduin2017/HowToCook/blob/master/tips/%25E5%258E%25A8%25E6%2588%25BF%25E5%2587%2586%25E5%25A4%2587.md
第一个是github pc上打开的，可以正常使用，第二个我通过app打开的，会404，我见到的排查了一下，第二个url应该是经过了2次urlEncode转换，所以会导致404 
 >iOS15.4 - iPhone 13 Pro - ZLGithubClient1.1.0(46)

**Comment by ExistOrLive** [comment]
非常感谢您的反馈，该问题将在 1.2.0 中解决。 

如果您觉的项目和应用还不错的话，希望您能给个好评或者星星 ^_^
