### ISSUE TITLE
Feedback: 大佬，howtocook的教程，点链接点进去会现实404，但我看了原文并没有并删除，这个是软件跳转的页面，烦请排查～https://github.com/Anduin2017/HowToCook/blob/master/tips/learn/%25E5%25BE%25AE%25E6%25B3%25A2%25E7%2582%2589.md

### ISSUE THREAD

**Issue by lazygoat644** [ExistOrLive/GithubClient#53]
大佬，howtocook的教程，点链接点进去会现实404，但我看了原文并没有并删除，这个是软件跳转的页面，烦请排查～https://github.com/Anduin2017/HowToCook/blob/master/tips/learn/%25E5%25BE%25AE%25E6%25B3%25A2%25E7%2582%2589.md 
 >iOS15.4.1 - iPhone 12 - ZLGithubClient1.1.0(46)

**Comment by ExistOrLive** [comment]
该问题将于1.2.0修复；您可以先尝试 [TestFlight Beta](https://testflight.apple.com/join/kCFO5joL) 体验

**Comment by ExistOrLive** [comment]
如果您觉的项目和应用还不错的话，希望您能给个好评或者星星 ^_^
