### ISSUE TITLE
Feedback: Why I can see pr in the issues?

### ISSUE THREAD

**Issue by Oliverwqcwrw** [ExistOrLive/GithubClient#54]
Why I can see pr in the issues? 
 >iOS15.4.1 - iPhone 12 mini - ZLGithubClient1.2.0(188)

**Comment by ExistOrLive** [comment]
Please refer to [list-repository-issues](https://docs.github.com/en/rest/reference/issues#list-repository-issues)
<img width="1149" alt="截屏2022-04-14 下午1 07 21" src="https://user-images.githubusercontent.com/18443373/163317671-96611781-4892-46dd-a403-db4cc10c95a6.png">

**Comment by Oliverwqcwrw** [comment]
OK From: ***@***.*** ***@***.***> on behalf of 朱猛 ***@***.***>Sent: Thursday, April 14, 2022 13:09To: ExistOrLive/GithubClient ***@***.***>Cc: Oliver ***@***.***>; Author ***@***.***>Subject: Re: [ExistOrLive/GithubClient] Feedback: Why I can see pr in the issues? (Issue #54) 

Please refer to list-repository-issues





—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>


Get Outlook for iOS
