### ISSUE TITLE
Feedback: 如何打赏

### ISSUE THREAD

**Issue by NJUyued** [ExistOrLive/GithubClient#55]
如何打赏 
 >iOS15.4 - iPhone 12 - ZLGithubClient1.1.0(46)

**Comment by ZXHubs** [comment]
您好，请问「打赏」是具体指的什么功能呢？能详细说明一下嘛

**Comment by NJUyued** [comment]
感觉您们做的很好，想给作者们打赏一些钱，支持一下你们的工作，一些微薄之力，也许也有别的人想给你们支持
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2022年4月20日(星期三)&nbsp;晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[ExistOrLive/GithubClient]&nbsp;Feedback:&nbsp;如何打赏&nbsp;(Issue&nbsp;#55)



 
您好，请问「打赏」是具体指的什么功能呢？能详细说明一下嘛
 
&mdash;

**Comment by ZXHubs** [comment]
非常感谢您对项目的支持和认可。链接在这：https://gitee.com/existorlive/exist-or-live-pic/raw/master/IMG_4232.JPG

**Comment by NJUyued** [comment]
好的，已打赏，感谢您们对开源社区的贡献
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2022年4月20日(星期三)&nbsp;晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[ExistOrLive/GithubClient]&nbsp;Feedback:&nbsp;如何打赏&nbsp;(Issue&nbsp;#55)



 
非常感谢您对项目的支持和认可。链接在这：https://gitee.com/existorlive/exist-or-live-pic/raw/master/IMG_4232.JPG
 
&mdash;
