### ISSUE TITLE
Feedback: 不知道为什么，返回键总是失效……点了没反应

### ISSUE THREAD

**Issue by YunDuanCode** [ExistOrLive/GithubClient#56]
不知道为什么，返回键总是失效……点了没反应 
 >iPadOS15.4.1 - iPad Pro 11-inch - ZLGithubClient1.2.0(187)

**Comment by ZXHubs** [comment]
请问一下手势「右滑返回」会失效吗？仅仅是通过「返回按钮」返回上一级才没有反应？

**Comment by YunDuanCode** [comment]
嗯……它大多数时候很正常，但是某些页面的返回键是不能点击的，而且滑动也无法返回，只能通过重启应用解决；但是这种事故似乎是偶然性的，即使是同一个页面，有的时候会失效，有点时候又有效。

**Comment by YunDuanCode** [comment]
而且右滑返回似乎在任何情况下都无法使用

**Comment by ZXHubs** [comment]
暂时未能复现问题，我们会持续跟踪。

**Comment by YunDuanCode** [comment]
经常出现：进入某个项目/项目问题/项目代码，之后返回键就没有反应了。大部分时候是正常的

**Comment by YunDuanCode** [comment]
包括我刚才评论完这个问题之后，也无法返回，只能退出重进

**Comment by YunDuanCode** [comment]
现在看来，只有打开项目时会出现此问题。

**Comment by ZXHubs** [comment]
我们将会排查一下原因。您可以尝试iOS系统级返回手势。 「从屏幕最左边向右滑返回」。（评论页面不支持）

**Comment by YunDuanCode** [comment]
现在似乎一切正常了

**Comment by YunDuanCode** [comment]
右滑返回也可以使用了，可能是之前的操作问题。非常感谢
