### ISSUE TITLE
通知已读与评论优化

### ISSUE THREAD

**Issue by AjianYo** [ExistOrLive/GithubClient#77]
嗨，谢谢你们开发的app！
请问可以在通知中增加已读功能吗？还有评论功能可以和官网一样“引用”“拷贝链接”吗？

**Comment by ExistOrLive** [comment]
你好，非常感谢你的建议。通知已读功能当前版本中已经支持了；评论功能的引用和拷贝链接功能会在后续版本中安排。
![20230702-170005](https://github.com/ExistOrLive/GithubClient/assets/18443373/ebd7bb38-1867-4ca2-b9f6-bfa2281a65d7)

**Comment by AjianYo** [comment]
> 你好，非常感谢你的建议。通知已读功能当前版本中已经支持了；评论功能的引用和拷贝链接功能会在后续版本中安排。
> ![20230702-170005](https://user-images.githubusercontent.com/18443373/250346112-ebd7bb38-1867-4ca2-b9f6-bfa2281a65d7.jpeg)

好的，谢谢👍
