### ISSUE TITLE
显示出错

### ISSUE THREAD

**Issue by YYLWZDXPGD** [ExistOrLive/GithubClient#78]
![IMG_4509](https://github.com/ExistOrLive/GithubClient/assets/128379352/0bf597ff-f130-46bc-8e12-69f27b256b6d)
如图，Jonathan的头像怎么到了上面的，LHMTR的也是

**Comment by ExistOrLive** [comment]
非常感谢你的反馈；我们会尽快修复该问题

**Comment by YYLWZDXPGD** [comment]
最近仍然会发生此问题，请尽快修复
