### ISSUE TITLE
非默认分支无法查看代码；组织无显示；反馈无法提交；有时查看代码自动跳转至web界面

### ISSUE THREAD

**Issue by CNenfan** [ExistOrLive/GithubClient#83]
非默认分支无法查看代码；组织无显示；反馈无法提交；有时查看代码自动跳转至web界面

iphone8
ios15.6

**Comment by CNenfan** [comment]
选中非默认分支，点开代码查看，是默认分支的文件

**Comment by ExistOrLive** [comment]
将在1.6.0版本修复

**Comment by CNenfan** [comment]
组织还是未能显示
包括自己创建和加入的
辛苦作者大大了

**Comment by ExistOrLive** [comment]
重新登陆，在授权时给予组织相关权限；如果使用access token，请确保access token 有组织的权限
